version: '3'

services:
  ingress:
      build: ./ingress
      image: ingress:latest
      volumes:
        - ./ingress/nginx.conf:/etc/nginx/nginx.conf
        - ./ingress/conf.d:/etc/nginx/conf.d
        - /var/log/nginx:/var/log/nginx
      ports:
        - 80:80
      hostname: ingress
      restart: unless-stopped

  green-backend:
      build: ./backend
      image: backend:latest
      volumes:
        - /var/log/green-backend:/var/log
      hostname: green-backend
      restart: unless-stopped

  blue-backend:
      build: ./backend
      image: backend:latest
      volumes:
        - /var/log/blue-backend:/var/log
      hostname: blue-backend
      restart: unless-stopped
